# Use postgres/example user/password credentials
version: '3.1'

services:
  training-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword

  adminer:
    image: adminer
    restart: always
    ports:
      - 8282:8080
